mspam.views.Home=Ext.extend(Ext.Panel,{

	layout:'card',	
	
	dockedItems:[
	{
		itemId:'titleToolbar',
		xtype:'toolbar',
		dock:'top',
		ui:'light',
		title:'Spam',
		items:[
		{
			iconCls:'refresh',
			iconMask:true,
			ui:'plain',
			handler:function(){
				Ext.dispatch({
					controller:'Home',
					action:'getSearchResponse'
				});
			}
		},
		{
			xtype:'spacer'
		},
		{
			iconCls:'settings',
			iconMask:true,
			ui:'plain',
			handler:function(){
				Ext.dispatch({
					controller:'menu',
					action:'showSettingsSheet',
					view:this.up('home')
				})
			}
		},
		{
			iconCls:'search',
			iconMask:true,
			ui:'plain',
			handler:function(){
				Ext.dispatch({
					controller:'search',
					action:'showSearchForm',
					view:this.up('home')
				})
			}
		}]
	}]
	
});
Ext.reg('home',mspam.views.Home);
